feat: add custom uns service flag
unik-name/uns-cli pull request #146
Opened 2020-10-13 14:34 UTC by peterjah

2020-10-13 14:34 UTC, dlecan commented
https://spacelephant.tpondemand.com/entity/3023

2020-10-20 11:38 UTC, ftreguer requested changes

2020-10-20 11:38 UTC, ftreguer commented on src/sdkWrapper.ts
>          const transactionResult: IProcessorResult = await this.unsClient.transaction.send(transaction);
Schema error not handled here

2020-10-20 12:04 UTC, ftreguer approved these changes

2020-10-20 13:16 UTC, merged