feat: get pioneer badge value from sdk
unik-name/uns-cli pull request #154
Opened 2020-11-04 15:01 UTC by peterjah

2020-11-04 15:01 UTC, dlecan commented
https://spacelephant.tpondemand.com/entity/3094

2020-11-05 11:08 UTC, ftreguer requested changes

2020-11-05 11:08 UTC, ftreguer commented on src/commands/badges/claim.ts
>      }
check if badge in undefined or not change (if sdk don't returns error for that)

2020-11-05 17:37 UTC, ftreguer approved these changes

2020-11-05 17:45 UTC, merged