Is disclosed
unik-name/uns-cli pull request #18
Opened 2019-10-25 07:59 UTC by peterjah

Is-disclosed CLI command.
rebased on "disclose" branch
to be rebased on master when disclose branch will be merget

2019-10-28 13:53 UTC, ftreguer requested changes

2019-10-28 13:53 UTC, ftreguer commented on src/commands/is-disclosed.ts
> +        ...unikidFlag("The UNIK token"),
You have to use an argument, not a flag

2019-10-28 13:53 UTC, ftreguer commented on src/commands/is-disclosed.ts
> +        `$ uns is-disclosed --unikid 636795fff13c8f2d2fd90f9aa124d7f583920fce83588895c917927ee522db3b --network devnet`,
You have to use an argument, not a flag

2019-10-28 13:53 UTC, ftreguer commented on src/commands/is-disclosed.ts
> +export class IsDisclosedCommand extends GetPropertyValueCommand {
You should not extend GetPropertyValueCommand, this command use required flags that we don't need is is-disclosed command.

2019-10-28 13:53 UTC, ftreguer commented on src/commands/is-disclosed.ts
> +            const res = await super.do(flags);
And if you don't extend GetPropertyValueCommand, you can only call getProperty function with "explicitValue" property, or didResolve passedExplicitValue?explicitValue

2019-10-28 13:53 UTC, ftreguer commented on src/commands/is-disclosed.ts
> +            const res = await super.do(flags);
I think you want to pass explicitValue as property, but I don't see it in the code

2019-10-28 13:53 UTC, ftreguer commented on src/commands/is-disclosed.ts
> +                        isDisclosed: true,
Always true ?

2019-10-28 13:53 UTC, ftreguer commented on src/commands/is-disclosed.ts
> +                }
I think didResolve can do that for you

2019-11-06 11:06 UTC, peterjah commented on src/commands/is-disclosed.ts
> +                        isDisclosed: true,
Si la propriété existe oui (cf la spec). A ce que j'ai compris il devra toujours rester minimum une explicit si disclose à été appelé

2019-11-06 11:16 UTC, peterjah commented on src/commands/is-disclosed.ts
> +                }
How i am supposed to get the DID ??

2019-11-06 13:32 UTC, ftreguer requested changes

2019-11-06 13:32 UTC, ftreguer commented on src/commands/is-disclosed.ts
> +            if (error.message === "Not Found") {
You should use error.response.status instead of message, message could change :/

2019-11-06 13:32 UTC, ftreguer commented on src/commands/is-disclosed.ts
> +            data,
in specs yaml doesn't display data level, I think it's the same for json

2019-11-06 13:32 UTC, ftreguer commented on src/commands/is-disclosed.ts
> +            description: "The UNIK Id to check",
"The UNIK token to query." ?

2019-11-06 13:32 UTC, ftreguer commented on src/commands/is-disclosed.ts
> +        `$ uns is-disclosed --n devnet 636795fff13c8f2d2fd90f9aa124d7f583920fce83588895c917927ee522db3b`,
-n or --network

2019-11-06 13:32 UTC, ftreguer commented on src/commands/is-disclosed.ts
> +                const unik = await this.api.getUnikById(args.unikid);
Is this required to fetch unik ? No specific message for unik not found

2019-11-06 13:55 UTC, ftreguer approved these changes

2019-11-06 13:57 UTC, merged