Send command
unik-name/uns-cli pull request #20
Opened 2019-10-25 16:17 UTC by ftreguer

Add send command and tests [#1401](https://spacelephant.tpondemand.com/entity/1401-ron-je-veux-utiliser-greateruns-send)

2019-10-28 13:27 UTC, Nigui requested changes
- `src/utils.ts` starts to be fat and mixes functions with different purposes (create transaction, flag,...). Maybe it's time to split into multiple files. 
- where do you do these checks : 
  - » :stop: Recipient address does not match expected format;
  - » :stop: Wrong pass phrase format;
  - » :stop: Not enough tokens;

2019-10-28 13:27 UTC, Nigui commented on src/baseCommand.ts
> +    protected toSatoshi(value: number): number {
must be an utility function

2019-10-28 13:27 UTC, Nigui commented on src/utils.ts
> +function promptHidden(text: string): Promise<string> {
nip: `hiddenPrompt` is more correct.

2019-10-28 13:27 UTC, Nigui commented on test/__fixtures__/commands/send.ts
> +        exitCode: 1,
`Should exit with code 2 if...` but you expect `exitCode:1`
Same for the following tests

2019-10-28 13:27 UTC, Nigui commented on src/commands/send.ts
> +import { flags as oFlags } from "@oclif/command";
why ? I couldn't find any conflicts importing `flags` directly

2019-10-28 13:27 UTC, Nigui commented on src/commands/send.ts
> +        [noCheckFlagId]: oFlags.boolean({
use native oclif feature `--no-*` https://oclif.io/docs/flags.

> // boolean flags may be reversed with `--no-` (in this case: `--no-force`).
    // The flag will be set to false if reversed. This functionality
    // is disabled by default, to enable it:
    // allowNo: true

2019-10-28 13:27 UTC, Nigui commented on src/commands/send.ts
> +            parse: input => input.replace(",", "."),
I don't know what we want to prevent with this replacement but `,` character has different meaning based on country : 
- US/UK : `1,000.314`
- FR : `1000,314`
I think that we must keep it simple and force user to not use `,` character or look at good practices. Maybe we can ask to PO.

https://en.wikipedia.org/wiki/Decimal_separator

2019-10-28 13:27 UTC, Nigui commented on src/commands/send.ts
> +    protected async do(flags: Record<string, any>, args?: Record<string, any>): Promise<any> {
nip: it's good to isolate large algorithm steps to different functions but we can do better with stateless function in a separated file.

2019-10-28 13:27 UTC, Nigui commented on src/commands/send.ts
> +        if (isNaN(amount) || amount <= 0 || amountParts.length > 2) {
If you give that amount `1,000.314` you'll get the following error : `The amount should be a positive number`.
But `1,000.314` is a positive number.

Same wired error giving `to.to`

2019-10-28 13:27 UTC, Nigui commented on src/commands/send.ts
> +    private async checkAndConfirmTarget(checkExistence: boolean, to: string, amount: number) {
`Target` means `Recipient` ? 
Can code be consistent ?

2019-10-28 15:12 UTC, ftreguer commented on src/utils.ts
> +function promptHidden(text: string): Promise<string> {
depends on the meaning of the sentence :D

- prompt hidden input
- hidden input prompt

2019-10-28 15:13 UTC, ftreguer commented on test/__fixtures__/commands/send.ts
> +        exitCode: 1,
Yep, copy/paste...

2019-10-28 15:19 UTC, ftreguer commented on src/commands/send.ts
> +import { flags as oFlags } from "@oclif/command";
old conflict

2019-10-28 15:21 UTC, ftreguer commented on src/commands/send.ts
> +            parse: input => input.replace(",", "."),
In CLI, I don't think we have to take care of thousands separator

2019-10-28 15:21 UTC, ftreguer commented on src/commands/send.ts
> +            parse: input => input.replace(",", "."),
@laurentlourenco  ?

2019-10-28 15:24 UTC, ftreguer commented on src/commands/send.ts
> +        if (isNaN(amount) || amount <= 0 || amountParts.length > 2) {
@laurentlourenco ?

2019-10-28 15:41 UTC, ftreguer commented on src/commands/send.ts
> +            parse: input => input.replace(",", "."),
I remove the comma rewrite, and throw an exception if the amount contains one. Only one decimal point is allowed.

2019-10-28 16:04 UTC, ftreguer commented
> * `src/utils.ts` starts to be fat and mixes functions with different purposes (create transaction, flag,...). Maybe it's time to split into multiple files.

Done here: https://github.com/unik-name/uns-cli/pull/19

> * where do you do these checks :
>  
>   * » :stop: Recipient address does not match expected format;
>   * » :stop: Wrong pass phrase format;
>   * » :stop: Not enough tokens;

Not enough tokens is a chain error, we do not have to calculate the fees amount to know if wallet ahs enough tokens to proceed

2019-10-28 16:05 UTC, ftreguer commented on src/commands/send.ts
> +        [noCheckFlagId]: oFlags.boolean({
good idea!

2019-10-29 09:16 UTC, Nigui commented on src/commands/send.ts
> +        console.log(checkExistence);
to remove

2019-10-29 09:31 UTC, Nigui commented on src/commands/send.ts
> +            const exists = await this.checkTargetWalletExistence(recipient);
function still use `Target` keyword --> `Recipient`

2019-10-29 09:32 UTC, Nigui commented
1 comment = 1 commit is GREAT !
Just 2 small comments then you can merge without my validation.

2019-10-29 09:33 UTC, Nigui approved these changes

2019-10-29 09:47 UTC, merged