Get wallet address
unik-name/uns-cli pull request #24
Opened 2019-11-04 10:24 UTC by ftreguer

get-wallet-address command [#1188](https://spacelephant.tpondemand.com/entity/1188-ron-jutilise-greateruns-get-wallet-address)

2019-11-05 15:56 UTC, Nigui requested changes
no successful test cases ?

2019-11-05 15:56 UTC, Nigui commented on test/__fixtures__/commands/get-wallet-address.ts
> +        description: "Should exit with code 2 if network is not known",
it's not a command specific test

2019-11-05 15:56 UTC, Nigui commented on test/__fixtures__/commands/get-wallet-address.ts
> +        description: "Should exit with code 1 if UNIK from unikid is not found",
you must mock api in tests

2019-11-05 15:56 UTC, Nigui commented on src/commands/get-wallet-address.ts
> +export function formatOutput(
why not moving this function into a `helpers` folder like you've done for `send` transaction ?

2019-11-05 15:56 UTC, Nigui commented on src/commands/get-wallet-address.ts
> +    displayChainMeta: boolean,
I don't think that this boolean is useful. 
You can just check if `chainMeta` parameter is not `undefined`

2019-11-06 10:35 UTC, ftreguer commented
> no successful test cases ?

No more integration tests for CLI commands, just unit tests of some specific parts

2019-11-06 10:36 UTC, ftreguer commented on test/__fixtures__/commands/get-wallet-address.ts
> +        description: "Should exit with code 2 if network is not known",
Yep, it's the same on each command tests, we should create a base command tests that handle common flags errors

2019-11-07 07:21 UTC, ftreguer commented on src/commands/get-wallet-address.ts
> +export function formatOutput(
I'll do it after send command merge, to apply the same pattern

2019-11-07 07:23 UTC, ftreguer commented on src/commands/get-wallet-address.ts
> +    displayChainMeta: boolean,
A boolean flag can't be undefined, his default value is false.

2019-11-08 08:35 UTC, Nigui commented on test/__fixtures__/commands/get-wallet-address.ts
> +        description: "Should exit with code 1 if UNIK from unikid is not found",
this test can crash later when we'll have that `NOT_FOUND` unikid in chain `e1615becbd39ad96344919dffa7b972f293b0a3973b05145fd6d0a1a20cac169`

2019-11-08 08:36 UTC, Nigui approved these changes

2019-11-08 09:41 UTC, merged