fix: fix misspelling for set/unset commands
unik-name/uns-cli pull request #56
Opened 2020-01-03 14:19 UTC by dlecan

2020-01-03 14:19 UTC, dlecan commented
https://spacelephant.tpondemand.com/entity/2048

2020-01-06 07:06 UTC, ftreguer requested changes

2020-01-06 07:06 UTC, ftreguer commented on src/commands/properties/set.ts
> +        `$ uns properties:set --network ${getNetworksListListForDescription()} --unkiid {unikId}
--unikid

2020-01-06 08:59 UTC, dlecan commented on src/commands/properties/set.ts
> +        `$ uns properties:set --network ${getNetworksListListForDescription()} --unkiid {unikId}
Fixed

2020-01-06 09:02 UTC, ftreguer approved these changes

2020-01-06 09:14 UTC, merged