feat: adds delegate register command
unik-name/uns-cli pull request #61
Opened 2020-01-13 16:25 UTC by peterjah

2020-01-13 16:25 UTC, dlecan commented
https://spacelephant.tpondemand.com/entity/1247

2020-01-16 15:37 UTC, Nigui requested changes

2020-01-16 15:37 UTC, Nigui commented on src/abstract-register.ts
> +export abstract class AbstractDelegateRegisterCommand extends WriteCommand {
nit: it's more `AbstractDelegateCommand` because ` DelegateResignCommand extends AbstractDelegateRegisterCommand` is weired

2020-01-16 15:37 UTC, Nigui commented on src/commands/delegate/register.ts
> +            description: "The Unikname between double quote, or the unikid to unregister as delegate.",
to register*

2020-01-16 15:37 UTC, Nigui commented on src/abstract-register.ts
> +        const nonce = Utils.BigNumber.make(await this.api.getNonce(ownerAddress))
it's not really emitter wallet's nonce it's unik owner wallet nonce.

2020-01-16 17:04 UTC, Nigui approved these changes

2020-01-17 09:10 UTC, merged