fix: duplicate disclosed explicit values
unik-name/uns-cli pull request #83
Opened 2020-02-11 15:59 UTC by peterjah

2020-02-11 15:59 UTC, dlecan commented
https://spacelephant.tpondemand.com/entity/2311

2020-02-12 08:50 UTC, ftreguer submitted a review, later dismissed

2020-02-12 08:57 UTC, ftreguer requested changes

2020-02-12 08:57 UTC, ftreguer commented on src/commands/unik/disclose.ts
> +        new Set(listOfExplicitValues).forEach(async explicit => {
Just checked, no filter on original list is applied

2020-02-12 16:18 UTC, ftreguer approved these changes

2020-02-12 17:32 UTC, merged